url: https://joisig.com
title: joisig gone awol
name: joisig gone awol
description: Jói Sigurdsson's post-employment adventures

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minima
minima:
  social_links:
    twitter: joisig
    github: joisig
    facebook: joisig
    linkedin: joisig
    rss: rss
  date_format: "%Y-%m-%d"
