url: https://joisig.com
name: joisig gone awol
description: Jói Sigurdsson's post-employment adventures

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
