url: https://joisig.com
title: joisig gone awol
name: joisig gone awol
description: Jói Sigurdsson's post-employment adventures

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

disqus:
  shortname: joisigcom

twitter_username: joisig
github_username: joisig
facebook_username: joisig
linkedin_username: joisig
rss: RSS
date_format: "%Y-%m-%d"
#show_excerpts: true
